version: '2.1'

services:
#  orchestration-service:
#    image: docker.artifactory.reform.hmcts.net/probate/orchestration-service
#    container_name: submit-service
#    environment:
#      - SERVER_PORT=8888
#      - http_proxy=
#      - https_proxy=
#      - no_proxy=
#    ports:
#     - 8888:8888
#    depends_on:
#      - idam-api
#      - service-auth-provider-api

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    container_name: idam-api
    command: --wait-for-database 60
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - IDAM_SUPERUSER_EMAIL=ccd@hmcts.net
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/idam
      - SPRING_MAIL_HOST=smtp-server
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - NOTIFY_API_KEY=AAAAAAAAAAAAAAAA
      - NOTIFY_CMC_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
      - NOTIFY_CMC_SOLICITOR_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
      - IDAM_SECRET=idam_test_secret
      - REFORM_ENVIRONMENT=test
      - NOTIFY=false
      - NOTIFY_CMC_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_SSCS_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_RESET_PASSWORD_TEMPLATE=fake
      - NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_PROBATE_BACKEND_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_CCD_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_BAR_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_FREG_ACTIVATE_USER_TEMPLATE=fake
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_CITIZEN=123456
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CMC_LEGAL=123456
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY=123456
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_PROBATE=123456
      - IDAM_API_OAUTH2_CLIENT_CLIENT_ID_PROBATE=123456
      - IDAM_PROBATE_WHITELIST=http://localhost:3451/oauth2redirect
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
      - 4501:8080
    depends_on:
      shared-database:
        condition: service_healthy

  shared-database:
    image: postgres:9.6-alpine
    container_name: shared-database
    ports:
      - 5342:5432
    healthcheck:
      test: psql -c 'select 1' -d postgres -U postgres
      retries: 2
    mem_limit: 160m
    memswap_limit: 0
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app:latest
    container_name: service-auth-provider-api
    environment:
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - JWT_KEY=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      - MICROSERVICEKEYS_EM_GW=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CCD_DATA=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CCD_DEFINITION=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CCD_GW=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CCD_PS=AAAAAAAAAAAAAAAA
      - TESTING_SUPPORT_ENABLED=true
      - MICROSERVICEKEYS_PROBATE_BACKEND=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_PROBATE_FRONTEND=AAAAAAAAAAAAAAAA
    ports:
      - 4502:8080

volumes:
  persistence-service-database-data:
